name: VoteReward
main: LDX\VoteReward\Main
version: 4.0.0
api: [5.1.0]
author: LDX
website: "https://github.com/LDX-MCPE/VoteReward"
load: POSTWORLD
commands:
  vote:
    usage: "/vote"
    description: "Checks to see if you've voted yet."
    permission: votereward.command.vote
permissions:
  votereward:
    default: false
    description: "Allows access to all VoteReward features."
  votereward.command:
    default: false
    description: "Allows access to all VoteReward commands."
  votereward.command.vote:
    default: true
    description: "Allows access to using the vote command."
  votereward.command.reload:
    default: op
    description: "Allows access to the vote reload subcommand."